language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - pypy3

services:
  - xvfb

addons:
  apt:
    packages:
    - wkhtmltopdf
    - xvfb
    - pandoc

install:
  - make setup

script:
  - make test

after_success: bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pypi
  username: "__token__"
  password: $PYPI_TOKEN
  on:
    tags: true
    python: "3.9"
