language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9

services:
  - xvfb

addons:
  apt:
    packages:
    - wkhtmltopdf
    - xvfb
    - pandoc

install:
  - make setup

script:
  - make test
