language: python
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9

before_script:
  - sh ./travis/init.sh
  - pip install codecov

script:
  - nosetests --with-coverage --cover-package=imgkit --where test imgkit_test.py
  - codecov

before_deploy: sh ./travis/pandoc.sh
